<?xml version="1.0" standalone="yes"?><!--DVdevice.xmlAdobe Premiere list of supported DV camcorders/VTRs and other devicesbuild 93 on 7/29/2003 2:44Devices are organized by:   video format (NTSC, PAL)   brand/manufacturer (Canon, JVC, Panasonic, Sony, etc)   Profile (collection of unique characteristics of devices by a given manufacturer)Each device profile has an optional list of attributes, consisting of a keyword and value.Currently recognized attributes:  CLASS N   N is an integer that selects a group of software processing      algorithms appropriate for a class of DV devices, with 0      choosing the basic algorithms that work for all devices.      Other values select algorithms that optimize the behavior of the      particular class of devices, but may not work correctly for      devices that are not part of the class. If no class      attribute is specified, the default 0 is used.  STEPSIZE N  N is an integer that specifies the number of single-step      commands that are needed to advance the device one video frame.      If not specified, 1 step is used. Some devices need the value 2      to step 2 fields (one frame) at a time.  DELAYRECORD N  N is an integer that specifies the number of milliseconds      Premiere Pro should wait before beginning playback during Export to      Tape. This is to compensate for devices that begin recording after       they report that they have begun, consequently cutting off the       first few frames of exported movies. If not specified, playback       begins when the device reports that it is recording.CHANNELCOMPLIANT Boolean  If this attribute is "No", it indicates that the      selected device always broadcasts data on IEEE1394 channel 63, even       if instructed to do otherwise.Other attributes are available but as yet undocumented. Send email to mydvdevices@adobe.com for further information.--><!DOCTYPE DVDEVICES [<!ELEMENT DVDEVICES (VIDEOFORMAT+)><!ELEMENT VIDEOFORMAT (NAME, BRAND+)><!ELEMENT NAME (#PCDATA)><!ELEMENT BRAND (NAME, MODEL+)><!ELEMENT MODEL EMPTY><!ATTLIST VIDEOFORMAT><!ATTLIST NAME><!ATTLIST BRAND><!ATTLIST MODEL    NAME CDATA #REQUIRED    CLASS CDATA #REQUIRED    STEPSIZE CDATA #IMPLIED    CHANNELCOMPLIANT CDATA #IMPLIED    NORMALSEARCHDISTANCE CDATA #IMPLIED    SLOWESTSEARCHDISTANCE CDATA #IMPLIED    FRAMESEARCHDISTANCE CDATA #IMPLIED    DELAYSTEPFORWARD CDATA #IMPLIED    DELAYSTEPREVERSE CDATA #IMPLIED    DELAYGETTCPLAY CDATA #IMPLIED    DELAYGETTCPAUSE CDATA #IMPLIED    DELAYSTARTGOTOPLAY CDATA #IMPLIED    DELAYSTARTGOTOPAUSE CDATA #IMPLIED    DELAYCONTINUEGOTOSWITCHPAUSE CDATA #IMPLIED    DELAYCONTINUEGOTOSWITCHREVERSE CDATA #IMPLIED    DELAYCONTINUEGOTOSLOWEST CDATA #IMPLIED    DELAYCONTINUEGOTOBUSY CDATA #IMPLIED    DELAYAFTERTIMEOUT CDATA #IMPLIED    DELAYTIMECODEQUERY CDATA #IMPLIED    DELAYRECORD CDATA #IMPLIED>]><DVDEVICES>   <!-- =================================== -->   <VIDEOFORMAT>      <NAME>NTSC</NAME>      <!-- =================================== -->      <!-- The "Generic" brand is available when a device is untested/unsupported -->      <BRAND>         <NAME>Générique</NAME>         <MODEL NAME="Standard" CLASS="0"/>         <MODEL NAME="Alterné 1" CLASS="1"/>         <MODEL NAME="Matériel HDV" CLASS="0"/>      </BRAND>      <BRAND>         <NAME>ADS</NAME>         <MODEL NAME="Standard" CLASS="6"/>         <MODEL NAME="Alterné 1" CLASS="7"/>      </BRAND>      <BRAND>         <NAME>Canon</NAME>         <MODEL NAME="Standard" CLASS="2"/>         <MODEL NAME="Alterné 1" CLASS="1"/>         <MODEL NAME="Alterné 2" CLASS="1" STEPSIZE="2"/>         <MODEL NAME="DM-GL1A" CLASS="2"/>         <MODEL NAME="DM-GL2A" CLASS="2"/>         <MODEL NAME="DM-PV1" CLASS="2"/>         <MODEL NAME="DM-XL1" CLASS="2"/>         <MODEL NAME="DM-XL1S" CLASS="2"/>         <MODEL NAME="DM-XV1" CLASS="2"/>         <MODEL NAME="DM-XV2" CLASS="2"/>         <MODEL NAME="Elura" CLASS="2"/>         <!--MODEL NAME="Elura10" CLASS="2"/ -->         <MODEL NAME="Elura2MC" CLASS="2"/>         <MODEL NAME="Elura20MC" CLASS="2"/>         <MODEL NAME="Elura40MC" CLASS="2"/>         <MODEL NAME="IXY-DV" CLASS="2"/>         <MODEL NAME="Optura" CLASS="2"/>         <MODEL NAME="Optura Pi" NORMALSEARCHDISTANCE="360" CLASS="2"/>         <MODEL NAME="Optura 100MC" CLASS="2"/>         <MODEL NAME="Optura 200MC" CLASS="2"/>         <MODEL NAME="ZR10" CLASS="2"/>         <MODEL NAME="ZR25MC" CLASS="2"/>         <MODEL NAME="ZR40" CLASS="2"/>         <MODEL NAME="ZR50MC" CLASS="2"/>         <MODEL NAME="ZR60" CLASS="2"/>         <MODEL NAME="ZR65MC" CLASS="2"/>         <MODEL NAME="ZR70MC" DELAYRECORD="440" CLASS="2"/>      </BRAND>      <BRAND>         <NAME>Canopus</NAME>         <MODEL NAME="Standard" CLASS="6"/>         <MODEL NAME="Alterné 1" CLASS="7"/>         <MODEL NAME="ADVC-100" CLASS="6"/>      </BRAND>      <BRAND>         <NAME>Dazzle</NAME>         <MODEL NAME="Standard" CLASS="6"/>         <MODEL NAME="Alterné 1" CLASS="7"/>      </BRAND>      <BRAND>         <NAME>Datavideo</NAME>         <MODEL NAME="Standard" CLASS="6"/>         <MODEL NAME="Alterné 1" CLASS="7"/>      </BRAND>      <BRAND>         <NAME>Hitachi</NAME>         <MODEL NAME="Standard" CLASS="1"/>         <MODEL NAME="Alterné 1" CLASS="0"/>      </BRAND>      <BRAND>         <NAME>JVC</NAME>         <MODEL NAME="Standard" CLASS="3" CHANNELCOMPLIANT="No"/>         <MODEL NAME="Alterné 1" CLASS="3" STEPSIZE="2" CHANNELCOMPLIANT="No"/>         <MODEL NAME="Alterné 2" DELAYRECORD="165" CLASS="3"/>         <MODEL NAME="Alterné 3" CLASS="1"/>         <MODEL NAME="Alterné 4" CLASS="1" STEPSIZE="2"/>         <MODEL NAME="BR-DV3000U" CLASS="3" STEPSIZE="1"/>         <MODEL NAME="BR-DV600U" CLASS="3" CHANNELCOMPLIANT="No"/>         <MODEL NAME="GR-DV2000U" CLASS="3" CHANNELCOMPLIANT="No"/>         <MODEL NAME="GR-DV3000U" CLASS="3"/>         <MODEL NAME="GR-DVL9500U" CLASS="3" STEPSIZE="2" CHANNELCOMPLIANT="No"/>         <MODEL NAME="GR-DVL9800U" CLASS="3" STEPSIZE="2" CHANNELCOMPLIANT="No"/>         <MODEL NAME="GR-DVL305U" CLASS="3" STEPSIZE="2" CHANNELCOMPLIANT="No"/>         <MODEL NAME="GR-DVL320U" CLASS="3"/>         <MODEL NAME="GR-DVL820U" CLASS="3"/>         <MODEL NAME="GR-DVL915U" CLASS="3" CHANNELCOMPLIANT="No"/>         <MODEL NAME="GR-DVL920U" CLASS="3"/>         <MODEL NAME="GY-DV500U" CLASS="3" CHANNELCOMPLIANT="No"/>         <MODEL NAME="HR-DVS1U" DELAYRECORD="165" CLASS="3" CHANNELCOMPLIANT="No"/>         <MODEL NAME="HR-DVS2U" CLASS="3" CHANNELCOMPLIANT="No"/>         <MODEL NAME="JY-VS200U" CLASS="3" STEPSIZE="1" CHANNELCOMPLIANT="No"/>         <!-- MODEL NAME="SR-VS20U" CLASS="3" CHANNELCOMPLIANT="No"/ -->      </BRAND>      <BRAND>         <NAME>Kyocera</NAME>         <MODEL NAME="Standard" CLASS="1"/>      </BRAND>      <BRAND>         <NAME>Media100</NAME>         <MODEL NAME="Standard" CLASS="6"/>         <MODEL NAME="Alterné 1" CLASS="7"/>      </BRAND>      <BRAND>         <NAME>Miglia</NAME>         <MODEL NAME="Standard" CLASS="6"/>         <MODEL NAME="Alterné 1" CLASS="7"/>         <MODEL NAME="Director's Cut Take 2" CLASS="6"/>      </BRAND>      <BRAND>         <NAME>Panasonic</NAME>         <MODEL NAME="Standard" CLASS="4" STEPSIZE="1"/>         <MODEL NAME="Alterné 1" CLASS="4" STEPSIZE="2"/>         <MODEL NAME="Alterné 2" DELAYRECORD="165" CLASS="1"/>         <MODEL NAME="Alterné 3" DELAYRECORD="165" CLASS="1" STEPSIZE="2"/>         <MODEL NAME="Alterné 4" CLASS="1"/>         <MODEL NAME="Alterné 5" CLASS="1" STEPSIZE="2"/>         <MODEL NAME="AG-DV1000P" CLASS="4" STEPSIZE="1"/>         <MODEL NAME="AG-DV2000P" CLASS="4" STEPSIZE="1"/>         <MODEL NAME="AG-DV2500P" CLASS="4" STEPSIZE="1"/>         <!--MODEL NAME="AG-DVC15P" CLASS="4" STEPSIZE="2"/ -->         <MODEL NAME="AG-DVX100P" DELAYRECORD="390" CLASS="4" STEPSIZE="1"/>         <MODEL NAME="AG-EZ30P" CLASS="4" STEPSIZE="2"/>         <MODEL NAME="AG-EZ50UP" CLASS="4" STEPSIZE="2"/>         <!-- MODEL NAME="AJ-D250P" CLASS="4" STEPSIZE="2"/ -->         <MODEL NAME="NV-C7" DELAYRECORD="360" CLASS="4" STEPSIZE="2"/>         <MODEL NAME="NV-DS9" DELAYRECORD="160" CLASS="4" STEPSIZE="2"/>         <MODEL NAME="NV-EX21" CLASS="4" STEPSIZE="2"/>         <MODEL NAME="NV-GS5K" CLASS="4" STEPSIZE="2"/>         <MODEL NAME="NV-GX7" DELAYRECORD="600" CLASS="4" STEPSIZE="1"/>         <MODEL NAME="NV-MX2500" CLASS="4" STEPSIZE="2"/>         <MODEL NAME="NV-MX3000" DELAYRECORD="165" CLASS="4" STEPSIZE="1"/>         <MODEL NAME="NV-MX5000" DELAYRECORD="600" CLASS="4" STEPSIZE="2"/>         <MODEL NAME="PV-DV102D" CLASS="4" STEPSIZE="1"/>         <MODEL NAME="PV-DV401D" CLASS="4" STEPSIZE="1"/>         <MODEL NAME="PV-DV402D" CLASS="4" STEPSIZE="1"/>         <MODEL NAME="PV-DV51D" DELAYRECORD="90" CLASS="4" STEPSIZE="1"/>         <MODEL NAME="PV-DV600D" CLASS="4" STEPSIZE="2"/>         <MODEL NAME="PV-DV702" CLASS="4" STEPSIZE="1"/>         <MODEL NAME="PV-DV852" CLASS="4" STEPSIZE="1"/>         <MODEL NAME="PV-DV901" CLASS="4" STEPSIZE="1"/>         <MODEL NAME="PV-DV910" CLASS="4" STEPSIZE="2"/>         <MODEL NAME="PV-DV951D" CLASS="4" STEPSIZE="1"/>      </BRAND>      <BRAND>         <NAME>ProMax</NAME>         <MODEL NAME="Standard" CLASS="7" STEPSIZE="1"/>         <MODEL NAME="Alterné 1" CLASS="7" STEPSIZE="2"/>         <MODEL NAME="Alterné 2" CLASS="6"/>         <MODEL NAME="DA-MAX+" DELAYRECORD="1000" CLASS="7"/>      </BRAND>      <BRAND>         <NAME>Power R</NAME>         <MODEL NAME="Standard" CLASS="6"/>         <MODEL NAME="Director's Cut" CLASS="6"/>      </BRAND>      <BRAND>         <NAME>Samsung</NAME>         <MODEL NAME="Standard" CLASS="0"/>         <MODEL NAME="Alterné 1" CLASS="1"/>      </BRAND>      <BRAND>         <NAME>Sharp</NAME>         <MODEL NAME="Standard" CLASS="5"/>         <MODEL NAME="Alterné 1" CLASS="1"/>      </BRAND>      <BRAND>         <NAME>Sony</NAME>         <MODEL NAME="Standard" CLASS="1"/>         <MODEL NAME="Alterné 1" DELAYRECORD="165" CLASS="1"/>         <MODEL NAME="Alterné 2" CLASS="6"/>         <MODEL NAME="DCR-PC1" CLASS="1"/>         <MODEL NAME="DCR-PC100" CLASS="1"/>         <MODEL NAME="DCR-PC101" CLASS="1"/>         <MODEL NAME="DCR-PC110" CLASS="1"/>         <MODEL NAME="DCR-PC120BT" CLASS="1"/>         <MODEL NAME="DCR-PC5" CLASS="1"/>         <MODEL NAME="DCR-PC9" CLASS="1"/>         <MODEL NAME="DCR-TRV10" CLASS="1"/>         <MODEL NAME="DCR-TRV103" CLASS="1"/>         <MODEL NAME="DCR-TRV11" CLASS="1"/>         <MODEL NAME="DCR-TRV130" CLASS="1"/>         <MODEL NAME="DCR-TRV17L" CLASS="1"/>         <MODEL NAME="DCR-TRV18" CLASS="1"/>         <MODEL NAME="DCR-TRV240" CLASS="1"/>         <MODEL NAME="DCR-TRV25" CLASS="1"/>         <MODEL NAME="DCR-TRV27" CLASS="1"/>         <MODEL NAME="DCR-TRV30" CLASS="1"/>         <MODEL NAME="DCR-TRV310" CLASS="1"/>         <MODEL NAME="DCR-TRV330" CLASS="1"/>         <MODEL NAME="DCR-TRV50" CLASS="1"/>         <MODEL NAME="DCR-TRV530" CLASS="1"/>         <MODEL NAME="DCR-TRV6" CLASS="1"/>         <MODEL NAME="DCR-TRV70K" CLASS="1"/>         <MODEL NAME="DCR-TRV720" CLASS="1"/>         <MODEL NAME="DCR-TRV8" CLASS="1"/>         <MODEL NAME="DCR-TRV9" CLASS="1"/>         <MODEL NAME="DCR-TRV900" CLASS="1"/>         <MODEL NAME="DCR-TRV950" CLASS="1"/>         <MODEL NAME="DCR-VX1000" DELAYRECORD="165" CLASS="1"/>         <MODEL NAME="DCR-VX2000" CLASS="1"/>         <MODEL NAME="DSR-11" CLASS="1"/>         <MODEL NAME="DSR-1500A" CLASS="1"/>         <MODEL NAME="DSR-1800" CLASS="1"/>         <MODEL NAME="DSR-20" CLASS="1"/>         <MODEL NAME="DSR-25" CLASS="1"/>         <!-- MODEL NAME="DSR-250" CLASS="1"/ -->         <MODEL NAME="DSR-30" CLASS="1"/>         <!-- MODEL NAME="DSR-300" CLASS="1"/>         <MODEL NAME="DSR-300AL" CLASS="1"/-->         <MODEL NAME="DSR-40" CLASS="1"/>         <MODEL NAME="DSR-45" CLASS="1"/>         <!-- MODEL NAME="DSR-500WSL" CLASS="1"/ -->         <MODEL NAME="DSR-PD100" CLASS="1"/>         <MODEL NAME="DSR-PD150" CLASS="1"/>         <MODEL NAME="DSR-PDX10" CLASS="1"/>         <MODEL NAME="DVMC-DA1" CLASS="6"/>         <MODEL NAME="DVMC-DA2" CLASS="7"/>         <MODEL NAME="GV-D300" CLASS="1"/>         <MODEL NAME="GV-D900" CLASS="1"/>         <MODEL NAME="GV-D1000" CLASS="1"/>      </BRAND>      <BRAND>         <NAME>Victor</NAME>         <MODEL NAME="Standard" CLASS="3"/>         <MODEL NAME="Alterné 1" CLASS="1"/>         <MODEL NAME="GR-D70K" CLASS="3"/>         <MODEL NAME="GR-DV3000" CLASS="3"/>      </BRAND>      <BRAND>         <NAME>Videonics</NAME>         <MODEL NAME="Standard" CLASS="6"/>         <MODEL NAME="Alterné 1" CLASS="1"/>      </BRAND>   </VIDEOFORMAT>   <!-- =================================== -->   <!-- =================================== -->   <VIDEOFORMAT>      <NAME>PAL</NAME>      <!-- =================================== -->      <!-- =================================== -->      <!-- The "Generic" brand is available when a device is untested/unsupported -->      <!-- There is only one possible model, which is "Generic" -->      <BRAND>         <NAME>Générique</NAME>         <MODEL NAME="Standard" CLASS="0"/>      </BRAND>      <BRAND>         <NAME>ADS</NAME>         <MODEL NAME="Standard" CLASS="6"/>         <MODEL NAME="Alterné 1" CLASS="7"/>      </BRAND>      <BRAND>         <NAME>Canon</NAME>         <MODEL NAME="Standard" CLASS="2"/>         <MODEL NAME="Alterné 1" CLASS="1"/>         <MODEL NAME="Alterné 2" CLASS="1" STEPSIZE="2"/>         <MODEL NAME="DM-MV20iE" CLASS="2"/>         <!-- MODEL NAME="MV430i MC" CLASS="2"/ -->         <MODEL NAME="XL1S" CLASS="2"/>         <MODEL NAME="DM-XM1E" CLASS="2"/>         <MODEL NAME="MV5iMC" CLASS="2"/>         <MODEL NAME="MVX2i" CLASS="2"/>         <MODEL NAME="XM-2" CLASS="2"/>      </BRAND>      <BRAND>         <NAME>Canopus</NAME>         <MODEL NAME="Standard" CLASS="6"/>         <MODEL NAME="Alterné 1" CLASS="7"/>         <MODEL NAME="ADVC-100" CLASS="6"/>      </BRAND>      <BRAND>         <NAME>Datavideo</NAME>         <MODEL NAME="Standard" CLASS="6"/>         <MODEL NAME="Alterné 1" CLASS="7"/>      </BRAND>      <BRAND>         <NAME>Grundig</NAME>         <MODEL NAME="Standard" CLASS="4" STEPSIZE="2"/>         <MODEL NAME="Alterné 1" CLASS="1"/>      </BRAND>      <BRAND>         <NAME>Hitachi</NAME>         <MODEL NAME="Standard" CLASS="1"/>      </BRAND>      <BRAND>         <NAME>JVC</NAME>         <MODEL NAME="Standard" CLASS="3"/>         <MODEL NAME="Alterné 1" CLASS="3" CHANNELCOMPLIANT="No"/>         <MODEL NAME="Alterné 2" CLASS="3" STEPSIZE="2" CHANNELCOMPLIANT="No"/>         <MODEL NAME="Alterné 3" CLASS="1"/>         <MODEL NAME="Alterné 4" CLASS="1" />         <MODEL NAME="BR-DV3000U" CLASS="3" STEPSIZE="1"/>         <MODEL NAME="GR-DVL800A" CLASS="3" STEPSIZE="2" CHANNELCOMPLIANT="No"/>         <MODEL NAME="GR-DVL9600E" CLASS="3" STEPSIZE="2" CHANNELCOMPLIANT="No"/>      </BRAND>      <BRAND>         <NAME>Miglia</NAME>         <MODEL NAME="Standard" CLASS="6"/>         <MODEL NAME="Alterné 1" CLASS="7"/>         <MODEL NAME="Director's Cut Take 2" CLASS="6"/>      </BRAND>      <BRAND>         <NAME>Panasonic</NAME>         <MODEL NAME="Standard" CLASS="4" STEPSIZE="2"/>         <MODEL NAME="Alterné 1" CLASS="1"/>         <MODEL NAME="Alterné 2" CLASS="1" STEPSIZE="2"/>         <MODEL NAME="AG-DV2500P" CLASS="4" STEPSIZE="1"/>         <!-- MODEL NAME="NV-DS28EN" CLASS="4" STEPSIZE="2"/ -->         <MODEL NAME="NV-DS77EN" CLASS="4" STEPSIZE="2"/>         <MODEL NAME="NV-EX1EN" CLASS="4" STEPSIZE="2"/>      </BRAND>      <BRAND>         <NAME>ProMax</NAME>         <MODEL NAME="Standard" CLASS="7" STEPSIZE="1"/>         <MODEL NAME="Alterné 1" CLASS="7" STEPSIZE="2"/>         <MODEL NAME="Alterné 2" CLASS="6"/>         <MODEL NAME="DA-MAX+" DELAYRECORD="1000" CLASS="7"/>      </BRAND>      <BRAND>         <NAME>Samsung</NAME>         <MODEL NAME="Standard" CLASS="0"/>         <MODEL NAME="Alterné 1" CLASS="1"/>      </BRAND>      <BRAND>         <NAME>Sony</NAME>         <MODEL NAME="Standard" CLASS="1"/>         <MODEL NAME="Alterné 1" DELAYRECORD="165" CLASS="1"/>         <MODEL NAME="DCR-PC100E" CLASS="1"/>         <MODEL NAME="DCR-PC101E" CLASS="1"/>         <MODEL NAME="DCR-PC120E" CLASS="1"/>         <MODEL NAME="DCR-PC2E" CLASS="1"/>         <MODEL NAME="DCR-PC9E" CLASS="1"/>         <MODEL NAME="DCR-TRV17E" CLASS="1"/>         <MODEL NAME="DCR-TRV18E" CLASS="1"/>         <MODEL NAME="DCR-TRV20E" CLASS="1"/>         <MODEL NAME="DCR-TRV25E" CLASS="1"/>         <MODEL NAME="DCR-TRV30E" CLASS="1"/>         <MODEL NAME="DCR-TRV310E" CLASS="1"/>         <!-- MODEL NAME="DCR-TRV330E" CLASS="1"/ -->         <MODEL NAME="DCR-TRV50E" CLASS="1"/>         <MODEL NAME="DCR-TRV9E" CLASS="1"/>         <MODEL NAME="DCR-TRV940E" CLASS="1"/>         <!-- MODEL NAME="DSR-500WSPL" CLASS="1"/ -->         <MODEL NAME="DCR-TRV950E" CLASS="1"/>         <MODEL NAME="DSR-11" CLASS="1"/>         <MODEL NAME="DSR-25" CLASS="1"/>         <MODEL NAME="DSR-45P" CLASS="1"/>         <MODEL NAME="DSR-PD150P" CLASS="1"/>         <MODEL NAME="DSR-PDX10P" CLASS="1"/>      </BRAND>      <BRAND>         <NAME>Thomson</NAME>         <MODEL NAME="Standard" CLASS="3"/>         <MODEL NAME="Alterné 1" CLASS="1"/>      </BRAND>   </VIDEOFORMAT></DVDEVICES>